@TodoApi_HostAddress = http://localhost:5059

GET {{TodoApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST https://localhost:7234/api/todoitems
Content-Type: application/json

{
  "name": "не забудь фрукти"
}
###
GET http://localhost:5059/api/todoitems

###

POST http://localhost:5059/api/todoitems
Content-Type: application/json

{
    "name": "Test task",
    "isComplete": false
}

### User adding
POST http://localhost:5059/api/User
Content-Type: application/json

{
    "userName": "testuser",
    "password": "1234"
}

### User check
GET http://localhost:5059/api/User?username=testuser&password=1234

